<?php
// Automatically Generated by TestLink Installer
define('DB_TYPE', 'mysqli');
define('DB_USER', 'fluke_user');
define('DB_PASS', 'S@marco1720');
define('DB_HOST', 'robb0376.publiccloud.com.br');
define('DB_NAME', 'fluke_teste');
define('DB_TABLE_PREFIX', '');
?>
