<?php
// Automatically Generated by TestLink Installer
define('DB_TYPE', 'mysqli');
define('DB_USER', 'b6524589e4abc1');
define('DB_PASS', 'e254df5b');
define('DB_HOST', 'us-cdbr-east-05.cleardb.net');
define('DB_NAME', 'heroku_e8d6728b75512a7');
define('DB_TABLE_PREFIX', '');
?>
