<?php
// Automatically Generated by TestLink Installer
define('DB_TYPE', 'mysqli');
define('DB_USER', 'root');
define('DB_PASS', 'mysql');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
?>
